name: bignumber
description: Dart Package for working with big numbers that only limited by memory size.
version: 0.0.1
homepage: https://github.com/namini40/big-number

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.16.0
